### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by AugustMiller** [AugustMiller/rick#2]
Essentially and alias, `rick server` ought to start up a simple PHP server. If we can't safely randomize the port, we'll need to allow a port to be set so there aren't conflicts with other projects.
- [x] Alias `php -S localhost:8000`
- [x] Port selection through `--port` flag

**Comment by jackjennings** [comment]
I'd prefer a consistent default port with the ability to change it as needed.

**Comment by jackjennings** [comment]
Here's the relevant implementation from Symfony: https://github.com/symfony/FrameworkBundle/blob/master/Command/ServerRunCommand.php
