### ISSUE TITLE
Symfony Components

### ISSUE THREAD

**Issue by AugustMiller** [AugustMiller/rick#5]
Logging these, here, because they appear to provide the kinds of functionality we're looking for:
- [Console](http://symfony.com/doc/current/components/console/index.html) allows us to build and [test](http://symfony.com/doc/current/components/console/introduction.html#testing-commands) console commands with lots of awesome options for I/O, including color, tables, selection menus, etc.
- [Process](http://symfony.com/doc/current/components/process.html) should help with any system commands, like `clone`ing, `curl`ing, in addition to the core `rick server` alias.

**Comment by jackjennings** [comment]
Pulled both of these in for #2, so closing.
